#!/command/with-contenv sh
while [ ! -f /var/run/avahi-daemon/pid ]; do
  echo "s6-rc: warning: avahi is not running, sleeping for 1 seconds before trying to start shairport-sync"
  sleep 1
done
echo "Starting shairport-sync"
exec /usr/local/bin/shairport-sync
